# Generated by Django 6.0.2 on 2026-03-25 17:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_attendancesession_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancesession',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
