# Generated by Django 6.0.2 on 2026-03-27 05:41

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_coursematerial_file_alter_video_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='coursematerial',
            name='file',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
    ]
