# Generated by Django 6.0.2 on 2026-04-01 09:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_course_image_alter_coursematerial_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='video',
        ),
        migrations.AddField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='courses/thumbnails/'),
        ),
        migrations.AddField(
            model_name='video',
            name='video_file',
            field=models.FileField(default=django.utils.timezone.now, upload_to='courses/videos/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coursematerial',
            name='file',
            field=models.FileField(upload_to='course_materials/'),
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
